"""initial_schema

Revision ID: 5c0dfde060d2
Revises: 
Create Date: 2026-09-10 21:16:16.277776+00:00

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '5c0dfde060d2'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('users',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('hashed_password', sa.String(length=255), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.CheckConstraint('LENGTH(TRIM(email)) > 0', name='ck_users_email_not_empty'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email')
    )
    op.create_table('accounts',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('user_id', sa.String(length=36), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('account_type', sa.String(length=20), nullable=False),
    sa.Column('currency', sa.String(length=3), nullable=False),
    sa.Column('opening_balance', sa.Numeric(precision=19, scale=4), nullable=False),
    sa.Column('current_balance', sa.Numeric(precision=19, scale=4), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.CheckConstraint("account_type IN ('checking', 'savings', 'credit', 'cash')", name='ck_accounts_account_type_valid'),
    sa.CheckConstraint('LENGTH(TRIM(name)) > 0', name='ck_accounts_name_not_empty'),
    sa.CheckConstraint('LENGTH(currency) = 3', name='ck_accounts_currency_length'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('accounts', schema=None) as batch_op:
        batch_op.create_index('idx_accounts_user_id', ['user_id'], unique=False)

    op.create_table('categories',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('user_id', sa.String(length=36), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('category_type', sa.String(length=10), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.CheckConstraint("category_type IN ('income', 'expense')", name='ck_categories_type_valid'),
    sa.CheckConstraint('LENGTH(TRIM(name)) > 0', name='ck_categories_name_not_empty'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id', 'name', name='uq_categories_user_name')
    )
    with op.batch_alter_table('categories', schema=None) as batch_op:
        batch_op.create_index('idx_categories_user_id', ['user_id'], unique=False)

    op.create_table('budgets',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('user_id', sa.String(length=36), nullable=False),
    sa.Column('category_id', sa.String(length=36), nullable=False),
    sa.Column('amount', sa.Numeric(precision=19, scale=4), nullable=False),
    sa.Column('month', sa.Integer(), nullable=False),
    sa.Column('year', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.CheckConstraint('amount > 0', name='ck_budgets_amount_positive'),
    sa.CheckConstraint('month >= 1 AND month <= 12', name='ck_budgets_month_valid'),
    sa.CheckConstraint('year >= 2000 AND year <= 2100', name='ck_budgets_year_valid'),
    sa.ForeignKeyConstraint(['category_id'], ['categories.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id', 'category_id', 'month', 'year', name='uq_budgets_user_category_month_year')
    )
    with op.batch_alter_table('budgets', schema=None) as batch_op:
        batch_op.create_index('idx_budgets_user_id', ['user_id'], unique=False)
        batch_op.create_index('idx_budgets_user_month_year', ['user_id', 'month', 'year'], unique=False)

    op.create_table('transfers',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('user_id', sa.String(length=36), nullable=False),
    sa.Column('from_account_id', sa.String(length=36), nullable=False),
    sa.Column('to_account_id', sa.String(length=36), nullable=False),
    sa.Column('amount', sa.Numeric(precision=19, scale=4), nullable=False),
    sa.Column('date', sa.Date(), nullable=False),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.CheckConstraint('amount > 0', name='ck_transfers_amount_positive'),
    sa.CheckConstraint('from_account_id != to_account_id', name='ck_transfers_different_accounts'),
    sa.ForeignKeyConstraint(['from_account_id'], ['accounts.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['to_account_id'], ['accounts.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('transfers', schema=None) as batch_op:
        batch_op.create_index('idx_transfers_from_account_id', ['from_account_id'], unique=False)
        batch_op.create_index('idx_transfers_to_account_id', ['to_account_id'], unique=False)
        batch_op.create_index('idx_transfers_user_id', ['user_id'], unique=False)

    op.create_table('transactions',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('account_id', sa.String(length=36), nullable=False),
    sa.Column('user_id', sa.String(length=36), nullable=False),
    sa.Column('category_id', sa.String(length=36), nullable=True),
    sa.Column('transfer_id', sa.String(length=36), nullable=True),
    sa.Column('transaction_type', sa.String(length=10), nullable=False),
    sa.Column('amount', sa.Numeric(precision=19, scale=4), nullable=False),
    sa.Column('date', sa.Date(), nullable=False),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.CheckConstraint("transaction_type IN ('income', 'expense')", name='ck_transactions_type_valid'),
    sa.CheckConstraint('amount > 0', name='ck_transactions_amount_positive'),
    sa.ForeignKeyConstraint(['account_id'], ['accounts.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['category_id'], ['categories.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['transfer_id'], ['transfers.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('transactions', schema=None) as batch_op:
        batch_op.create_index('idx_transactions_account_date', ['account_id', 'date'], unique=False)
        batch_op.create_index('idx_transactions_category_id', ['category_id'], unique=False)
        batch_op.create_index('idx_transactions_transfer_id', ['transfer_id'], unique=False)
        batch_op.create_index('idx_transactions_user_id', ['user_id'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('transactions', schema=None) as batch_op:
        batch_op.drop_index('idx_transactions_user_id')
        batch_op.drop_index('idx_transactions_transfer_id')
        batch_op.drop_index('idx_transactions_category_id')
        batch_op.drop_index('idx_transactions_account_date')

    op.drop_table('transactions')
    with op.batch_alter_table('transfers', schema=None) as batch_op:
        batch_op.drop_index('idx_transfers_user_id')
        batch_op.drop_index('idx_transfers_to_account_id')
        batch_op.drop_index('idx_transfers_from_account_id')

    op.drop_table('transfers')
    with op.batch_alter_table('budgets', schema=None) as batch_op:
        batch_op.drop_index('idx_budgets_user_month_year')
        batch_op.drop_index('idx_budgets_user_id')

    op.drop_table('budgets')
    with op.batch_alter_table('categories', schema=None) as batch_op:
        batch_op.drop_index('idx_categories_user_id')

    op.drop_table('categories')
    with op.batch_alter_table('accounts', schema=None) as batch_op:
        batch_op.drop_index('idx_accounts_user_id')

    op.drop_table('accounts')
    op.drop_table('users')
    # ### end Alembic commands ###
